# Generated by Django 2.0.6 on 2018-07-11 18:00

import app.models.region
import app.models.resource
from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('app', '0001_initial'), ('app', '0002_region_location'), ('app', '0003_auto_20180707_0058'), ('app', '0004_auto_20180707_0331'), ('app', '0005_region_boundary'), ('app', '0006_auto_20180709_0443'), ('app', '0007_region_owner'), ('app', '0008_auto_20180711_1759')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=app.models.region.default)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=app.models.resource.default)),
                ('region', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='resources', to='app.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(default='SRID=4326;POLYGON ((-85 -180, 85 -180, 85 180, -85 180, -85 -180))', srid=4326)),
            ],
        ),
        migrations.AddField(
            model_name='region',
            name='boundary',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='app.Feature'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='regions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
